#!/usr/bin/env bash


if [ "$1" == "" ]; then
  export COFFEA_IMAGE=coffeateam/coffea-dask:latest-py3.8
else
  export COFFEA_IMAGE=$1
fi

grep -v '^include' /etc/condor/config.d/01_cmslpc_interactive > .condor_config

SINGULARITY_SHELL=$(which bash) singularity exec -B ${PWD}:/srv -B /cvmfs -B /uscmst1b_scratch --pwd /srv \
  /cvmfs/unpacked.cern.ch/registry.hub.docker.com/${COFFEA_IMAGE} \
  /bin/bash --rcfile /srv/.bashrc
